%global tl_name dynamicnumber
%global tl_revision 38726

Name:		texlive-%{tl_name}
Epoch:		1
Version:	0.1.3
Release:	%{tl_revision}.1
Summary:	Dynamically typeset numbers and values in LaTeX through symbolic links
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/latex/contrib/dynamicnumber
License:	mit
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/dynamicnumber.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/dynamicnumber.doc.r%{tl_revision}.tar.xz
Source2:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/dynamicnumber.source.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
BuildRequires:	texlive-tlpkg
%texlive_base_requires
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
This package dynamically typesets values generated by different kinds of
scripts in LaTeX through the use of "symbolic links" (which are not in
any way related to the "symbolic links" used in UNIX systems!). The aim
is to reduce errors resulting from out-of-date numbers by directly
setting them in the number generating file and importing a "symbolic
link" into the LaTeX source file. It can be used to import not only
numerical values, but strings and pieces of code are also possible.
Currently only MATLAB and Python are supported to produce Dynamic Number
list files.

